import { Brain, Trophy, Users } from 'lucide-react';

export const features = [
    {
        icon: Brain,
        title: 'AI-Powered Quizzes',
        description:
            'Experience unique quizzes generated by advanced AI technology',
    },
    {
        icon: Users,
        title: 'Community Driven',
        description:
            'Join a vibrant community of quiz creators and participants',
    },
    {
        icon: Trophy,
        title: 'Competitive Rankings',
        description:
            'Compete globally and track your progress on our leaderboards',
    },
];

export const testimonials = [
    {
        text: 'Quiz Arena has transformed how I prepare for my exams. The AI-generated quizzes are incredibly helpful!',
        author: 'Sarah Johnson',
        role: 'Student',
    },
    {
        text: 'As a teacher, I love creating custom quizzes for my students. The platform is intuitive and engaging.',
        author: 'Michael Chen',
        role: 'Education Professional',
    },
    {
        text: "The competitive aspect keeps me coming back. It's both fun and educational!",
        author: 'Alex Rivera',
        role: 'Quiz Enthusiast',
    },
];
